#!/usr/bin/env bash
# repo-map.sh — Tier 0 (no AI) repository mapping.
#
# Produces a compact structural map of a repository using only deterministic
# tooling. This map is what gets handed to the explorer agent INSTEAD of
# letting the agent crawl the tree itself, which is the single largest
# token-cost lever in the documentation workflow.
#
# Usage:
#   ./repo-map.sh <repo-path> [output-path]
#
# Outputs markdown to stdout (or output-path) plus a token estimate on stderr.
#
# Hard requirements: bash, git, find, awk, sort
# Optional (better output if present): rg (ripgrep), tokei or cloc

set -euo pipefail

REPO="${1:?usage: repo-map.sh <repo-path> [output-path]}"
OUT="${2:-/dev/stdout}"

[[ -d "$REPO" ]] || { echo "error: $REPO is not a directory" >&2; exit 1; }
REPO="$(cd "$REPO" && pwd)"
NAME="$(basename "$REPO")"

have() { command -v "$1" >/dev/null 2>&1; }

# Prefer git's index: it already excludes vendored/ignored files, which is
# exactly the filter we want and is far faster than find + prune lists.
if git -C "$REPO" rev-parse --git-dir >/dev/null 2>&1; then
  IS_GIT=1
  mapfile -t FILES < <(git -C "$REPO" ls-files)
else
  IS_GIT=0
  mapfile -t FILES < <(cd "$REPO" && find . -type f \
    -not -path '*/.git/*' -not -path '*/node_modules/*' -not -path '*/vendor/*' \
    -not -path '*/.venv/*' -not -path '*/dist/*' -not -path '*/build/*' \
    -not -path '*/target/*' -not -path '*/__pycache__/*' | sed 's|^\./||')
fi

# ---------- helpers ----------

# Doc-ish paths. Deliberately kept as a single source of truth so that
# blind-worktree.sh and this script agree on what counts as documentation.
DOC_RE='(^|/)(README|CHANGELOG|CONTRIBUTING|ARCHITECTURE|DESIGN|HACKING|AGENTS|CLAUDE|NOTES|TODO)([^/]*)$|\.(md|mdx|rst|adoc|txt)$|(^|/)docs?/|(^|/)\.opencode/|(^|/)wiki/'

is_doc() { [[ "$1" =~ $DOC_RE ]]; }

bytes_of() { wc -c < "$REPO/$1" 2>/dev/null || echo 0; }

# ---------- accumulate ----------

declare -A EXT_COUNT EXT_BYTES
CODE_BYTES=0; DOC_BYTES=0; DOC_COUNT=0; TOTAL=0
DOC_LIST=()

for f in "${FILES[@]}"; do
  [[ -f "$REPO/$f" ]] || continue
  TOTAL=$((TOTAL+1))
  b=$(bytes_of "$f")
  if is_doc "$f"; then
    DOC_COUNT=$((DOC_COUNT+1)); DOC_BYTES=$((DOC_BYTES+b)); DOC_LIST+=("$f")
  else
    ext="${f##*.}"; [[ "$ext" == "$f" ]] && ext="(none)"
    EXT_COUNT["$ext"]=$(( ${EXT_COUNT["$ext"]:-0} + 1 ))
    EXT_BYTES["$ext"]=$(( ${EXT_BYTES["$ext"]:-0} + b ))
    CODE_BYTES=$((CODE_BYTES+b))
  fi
done

# ~3.5 bytes/token is a reasonable estimate for source code. Treat as an
# estimate, not a measurement: real tokenizers vary by 20-40%, and Anthropic
# models from 4.7 onward tokenize roughly 30% heavier than earlier ones.
est_tokens() { awk -v b="$1" 'BEGIN{printf "%d", b/3.5}'; }
CODE_TOK=$(est_tokens "$CODE_BYTES")
DOC_TOK=$(est_tokens "$DOC_BYTES")

# ---------- emit ----------

{
echo "# Repo map: $NAME"
echo
echo "Generated by repo-map.sh (deterministic, no AI). Treat all token figures as estimates."
echo

if [[ $IS_GIT -eq 1 ]]; then
  echo "- HEAD: \`$(git -C "$REPO" rev-parse --short HEAD 2>/dev/null || echo unknown)\`"
  echo "- Branch: \`$(git -C "$REPO" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)\`"
  echo "- Remote: \`$(git -C "$REPO" config --get remote.origin.url 2>/dev/null || echo none)\`"
  echo "- Commits: $(git -C "$REPO" rev-list --count HEAD 2>/dev/null || echo '?')"
  first=$(git -C "$REPO" log --reverse --format=%as 2>/dev/null | head -1 || true)
  last=$(git -C "$REPO" log -1 --format=%as 2>/dev/null || true)
  echo "- Active: ${first:-?} to ${last:-?}"
fi
echo "- Tracked files: $TOTAL (code: $((TOTAL-DOC_COUNT)), docs: $DOC_COUNT)"
echo "- Code size: $CODE_BYTES bytes (~$CODE_TOK tokens if fully read)"
echo "- Doc size: $DOC_BYTES bytes (~$DOC_TOK tokens)"
echo

echo "## Composition by extension"
echo
echo "| Ext | Files | Bytes | ~Tokens |"
echo "|---|---:|---:|---:|"
for ext in "${!EXT_COUNT[@]}"; do
  printf '%s\t%s\t%s\n' "$ext" "${EXT_COUNT[$ext]}" "${EXT_BYTES[$ext]}"
done | sort -t$'\t' -k3 -rn | head -20 | while IFS=$'\t' read -r e c b; do
  echo "| \`$e\` | $c | $b | $(est_tokens "$b") |"
done
echo

echo "## Top-level layout"
echo
echo '```'
(cd "$REPO" && find . -maxdepth 2 -type d \
  -not -path '*/.git*' -not -path '*/node_modules*' -not -path '*/vendor*' \
  -not -path '*/.venv*' -not -path '*/target*' -not -path '*/dist*' \
  | sed 's|^\./||' | sort | head -60)
echo '```'
echo

echo "## Manifests and build entry points"
echo
MANIFESTS='package.json|pnpm-workspace.yaml|turbo.json|nx.json|lerna.json|go.mod|go.work|Cargo.toml|pyproject.toml|setup.py|requirements.*\.txt|Pipfile|poetry.lock|Gemfile|composer.json|pom.xml|build.gradle.*|build.sbt|mix.exs|Makefile|Justfile|Taskfile.ya?ml|Dockerfile.*|docker-compose.*\.ya?ml|.*\.tf|Chart.ya?ml|skaffold.ya?ml'
found=0
for f in "${FILES[@]}"; do
  base="$(basename "$f")"
  if [[ "$base" =~ ^($MANIFESTS)$ ]]; then echo "- \`$f\`"; found=1; fi
done
[[ $found -eq 0 ]] && echo "_none detected_"
echo

echo "## CI / automation"
echo
found=0
for f in "${FILES[@]}"; do
  case "$f" in
    .github/workflows/*|.gitlab-ci.yml|.circleci/*|Jenkinsfile|.buildkite/*|azure-pipelines.yml|.woodpecker*|.drone.yml)
      echo "- \`$f\`"; found=1 ;;
  esac
done
[[ $found -eq 0 ]] && echo "_none detected_"
echo

echo "## Likely entry points"
echo
found=0
for f in "${FILES[@]}"; do
  base="$(basename "$f")"
  case "$f" in */node_modules/*|*/vendor/*) continue ;; esac
  if [[ "$base" =~ ^(main|index|app|server|cli|__main__|program|entrypoint)\.(go|rs|py|ts|tsx|js|jsx|mjs|java|kt|rb|php|cs|c|cpp)$ ]] \
     || [[ "$f" =~ (^|/)cmd/[^/]+/main\.(go)$ ]] \
     || [[ "$base" =~ ^(wsgi|asgi|manage)\.py$ ]]; then
    echo "- \`$f\`"; found=1
  fi
done
[[ $found -eq 0 ]] && echo "_none detected — check manifests above for scripts/targets_"
echo

echo "## Test layout"
echo
TEST_N=0
for f in "${FILES[@]}"; do
  if [[ "$f" =~ (^|/)(tests?|spec|__tests__|e2e|integration)/ ]] \
     || [[ "$f" =~ (_test|_spec|\.test|\.spec)\.[a-z]+$ ]]; then
    TEST_N=$((TEST_N+1))
  fi
done
echo "- Test files: $TEST_N"
for f in "${FILES[@]}"; do
  if [[ "$f" =~ (^|/)(tests?|spec|__tests__|e2e|integration)/ ]]; then
    dirname "$f"
  fi
done | sort -u | head -15 | sed 's/^/- `/;s/$/`/'
echo

if [[ $IS_GIT -eq 1 ]]; then
  echo "## Highest-churn files (last 12 months)"
  echo
  echo "Churn is the cheapest available proxy for 'load-bearing'. Read these first."
  echo
  # Docs are excluded: this list doubles as the explorer's reading list, and the
  # explorer must not be pointed at documentation.
  git -C "$REPO" log --since='12 months ago' --name-only --pretty=format: 2>/dev/null \
    | grep -v '^$' | grep -Ev "$DOC_RE" | sort | uniq -c | sort -rn | head -30 \
    | awk '{printf "- `%s` (%s commits)\n", $2, $1}' || echo "_unavailable_"
  echo
fi

echo "## Largest code files"
echo
for f in "${FILES[@]}"; do
  is_doc "$f" && continue
  [[ -f "$REPO/$f" ]] || continue
  printf '%s\t%s\n' "$(bytes_of "$f")" "$f"
done | sort -rn | head -20 | awk -F'\t' '{printf "- `%s` (%s bytes)\n", $2, $1}'
echo

if have rg; then
  echo "## Inline debt markers"
  echo
  for m in TODO FIXME HACK XXX DEPRECATED; do
    n=$(rg -c --no-filename --no-messages -w "$m" "$REPO" 2>/dev/null | awk '{s+=$1} END{print s+0}')
    echo "- $m: ${n:-0}"
  done
  echo
fi

echo "## Documentation inventory (PATHS ONLY — contents deliberately excluded)"
echo
echo "These are the audit targets for phase 3. The explorer agent must not read them."
echo
if [[ ${#DOC_LIST[@]} -eq 0 ]]; then
  echo "_no documentation found — skip phase 3, go straight to authoring_"
else
  for d in "${DOC_LIST[@]}"; do
    echo "- \`$d\` ($(bytes_of "$d") bytes)"
  done
fi
} > "$OUT"

# Cost signal on stderr so it doesn't pollute the map.
{
echo
echo "=== phase 1 cost estimate (ESTIMATE, not measured) ==="
echo "Full-read input tokens:        ~$CODE_TOK"
echo "Targeted-read (assume 12%):    ~$(awk -v t="$CODE_TOK" 'BEGIN{printf "%d", t*0.12}')"
echo
printf "At DeepSeek V4 Flash \$0.08/M in:  full \$%.4f | targeted \$%.4f\n" \
  "$(awk -v t="$CODE_TOK" 'BEGIN{print t/1000000*0.08}')" \
  "$(awk -v t="$CODE_TOK" 'BEGIN{print t*0.12/1000000*0.08}')"
printf "At GLM 5.2 \$0.50/M in:            full \$%.4f | targeted \$%.4f\n" \
  "$(awk -v t="$CODE_TOK" 'BEGIN{print t/1000000*0.50}')" \
  "$(awk -v t="$CODE_TOK" 'BEGIN{print t*0.12/1000000*0.50}')"
printf "At Claude Sonnet 5 \$2.00/M in:    full \$%.4f | targeted \$%.4f\n" \
  "$(awk -v t="$CODE_TOK" 'BEGIN{print t/1000000*2.00}')" \
  "$(awk -v t="$CODE_TOK" 'BEGIN{print t*0.12/1000000*2.00}')"
echo
echo "Note: single-pass input only. Agent loops re-send context each turn, so"
echo "multiply by observed turn count. This is why 'steps' caps matter."
} >&2
